title: TTWabbit Blog
description: Write ups and other stuff Cybersec related.
author: Antonio Tascón
github: https://github.com/TTWabbit
about: I'm a Cybersec enthusiast looking to make a career in the field.
disqus_shortname: ttwabbit
google_analytics: UA-190906841-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/TTWabbit"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ttwabbit/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/TTWabbit"

share:
  twitter_username: TTWabbit
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ttwabbit.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
